### ISSUE TITLE
LT-20 Latitude calculation

### ISSUE THREAD

**Issue by Dukat-Gul** [akenza-io/device-type-library#68]
Hi, 
Just wondering if you have double checked the calculations for the Latitude; Especially against the example provided in `globalsat/LT-20/uplink.spec.js`
`` data.longitude = (toLittleEndian(payload.substr(4, 6)) * 215) / 10 * 0.000001;``
``   data.latitude = (toLittleEndian(payload.substr(10, 6)) * 215) / 10 * 0.000001;``

as the manufacturers guide indicates a different value - which if you check against your `globalsat/LT-20/uplink.spec.js` doesnt work out mathematically.
![477274217a1bdf11324e04cb2892491f9f039361](https://user-images.githubusercontent.com/81039430/116844398-950ed500-ac15-11eb-9a31-ec14272a3d14.png)
![e431d93b4516de6b955e4d920e92d2e44f8625eb](https://user-images.githubusercontent.com/81039430/116844414-9cce7980-ac15-11eb-8a0a-9fbd9ec626cb.png)

`payload_hex:` "80029e3856005123424300",
<b>breakdown/deconstruct:</b>
80 <i> (Protocol Version) </i> 
02  <i> (Command ID) </i> 
9e3856  <i> (Longitude) </i> - converts to 56389e littleendian - 5386793 decimal * 215/10*0.000001 = 121.487685 - MATHS WORKS
005123 <i> (Latiitude) </i> - converts to 235100 littleendian - 2314496 decimal * 215/10*0.000001 = 49.761664 - aligned with the below - but NOT the example in the manufacturer guide.
     (latitude) - converts to 235100 littleendian - 2314496 decimal * 108/10*0.000001 = 24.9965568 - aligned with manufacturer example
42  
43
00

          `assert.equal(value.data.longitude,` 121.487685);
          `assert.equal(value.data.latitude,` 49.761663999999996);

Noting - I am having problems with that value - and am in search of a solution. As I am south of the equator and the negative is also causing issue(s).

**Comment by Dukat-Gul** [comment]
I see that a pull request is being processed, and the negative requirement I am working through with the Manufacturer seems to be common to others.

Should you have the need or desire - here is a sample of the output payload from my LT-20 unit and the current observed calculations/conversions.


`80023032525AEFD2046400 - Breakdown`
--

> 80` | Protocol Version

> 02` | Command ID

> 303252 | Longitude - converts to 523230 as little endian    Which converts to 5386800 as decimal then   multiply by 215 divide by 10 and multiple by 0.000001:   * 215/10 * 0.000001 = 115.8162   

This maths seems to work.
This aligns to my   location  Perth Western Australia: -31.95224, <b>115.8614</b> & more specifically Stirling -31.896675, <b>115.815534</b>

> 5AEFD2 | Latitude – converts to D2EF5A as little endian    Which converts to 13823834 as decimal then   multiply by 108 divide by 10 and multiple by 0.000001:   * 108/10 * 0.000001 = 149.2974072   

This maths seems to be broken – its not negative   nor 90 or 180 degress out. 
This **does not align** to my location of     Perth: <b>-31.95224 </b>, 115.8614 &   more specifically Stirling <b>-31.896675</b>, 115.815534

**Comment by J2thatsme** [comment]
Hi there @Dukat-Gul thanks for your input.
The issue lies in the false conversion to unsigned integer.
We will fix the bug in the coming days. 

Best Regards

J2

**Comment by J2thatsme** [comment]
Hi @Dukat-Gul 
There is now a fix deployed. Feel free to test it and give us feedback.

Best Regards

J2

**Comment by Dukat-Gul** [comment]
Thanks. I have been able to confirm the code changes (with some adaption to work in my environment) are now fully functional. I have referenced your efforts as well as another contributor.
